//VALIDACION
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const VALIDAR_FORMULARIO_EXITO = 'VALIDAR_FORMULARIO_EXITO';
export const VALIDAR_FORMULARIO_ERROR = 'VALIDAR_FORMULARIO_ERROR';


//USUARIO
export const AGREGAR_USUARIO = 'AGREGAR_USUARIO';
export const AGREGAR_USUARIO_EXITO = 'AGREGAR_USUARIO_EXITO';
export const AGREGAR_USUARIO_ERROR = 'AGREGAR_USUARIO_ERROR';

export const COMENZAR_USUARIOS_CARTAS = 'COMENZAR_USUARIOS_CARTAS';
export const DESCARGA_USUARIOS_EXITOSA = 'DESCARGA_USUARIOS_EXITOSA';
export const DESCARGA_USUARIOS_ERROR = 'DESCARGA_USUARIOS_ERROR';

export const OBTENER_USUARIO_ELIMINAR = 'OBTENER_USUARIO_ELIMINAR';
export const USUARIO_ELIMINADO_EXITO = 'USUARIO_ELIMINADO_EXITO';
export const USUARIO_ELIMINADO_ERROR = 'USUARIO_ELIMINADO_ERROR';

export const OBTENER_USUARIO_EDITAR = 'OBTENER_USUARIO_EDITAR';
export const USUARIO_EDITAR_EXITO = 'USUARIO_EDITAR_EXITO';
export const USUARIO_EDITAR_ERROR = 'USUARIO_EDITAR_ERROR';

export const COMENZAR_EDICION_USUARIO = 'COMENZAR_EDICION_USUARIO';
export const USUARIO_EDITADO_EXITO = 'USUARIO_EDITADO_EXITO';
export const USUARIO_EDITADO_ERROR = 'USUARIO_EDITADO_ERROR';

